name: Build Android APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: List files (Check what we have)
        run: ls -R

      - name: Unzip project
        run: unzip -q "iptv-player (2).zip" -d extracted_project

      - name: List files after unzip
        run: ls -R extracted_project

      - name: Build with Gradle
        run: |
          # البحث عن ملف gradlew داخل المجلد المستخرج
          GRADLEW=$(find extracted_project -name "gradlew" -type f | head -n 1)
          
          if [ -z "$GRADLEW" ]; then
            echo "خطأ: لم يتم العثور على ملف gradlew!"
            exit 1
          fi
          
          echo "تم العثور على الملف في: $GRADLEW"
          chmod +x "$GRADLEW"
          # الانتقال إلى المجلد الذي يحتوي على الملف للبدء
          cd "$(dirname "$GRADLEW")"
          ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: My-IPTV-App
          path: "**/build/outputs/apk/debug/*.apk"
